# Generated by Django 4.1.5 on 2023-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_origen', models.CharField(max_length=40)),
                ('idioma', models.CharField(max_length=40)),
            ],
        ),
    ]
